# 请先在security.http中运行登录测试以获取token

### 成功创建带图片的帖子
POST {{baseUrl}}/api/infor-flow/create
Content-Type: application/json
#Authorization: Bearer {{token}}

{
    "user_id": "{{userId}}",
    "content": "这是一个测试帖子，包含图片。",
    "type": "问答",
    "images": [
        "https://example.com/image1.png",
        "https://example.com/image2.png"
    ]
}

###
POST {{baseUrl}}/api/infor-flow/create
Content-Type: application/json
#Authorization: Bearer {{token}}

{
    "user_id": "{{userId}}",
    "type": "经验",
    "content": "帖子"
}

### 创建没有图片的帖子
POST {{baseUrl}}/api/infor-flow/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": "{{userId}}",
    "content": "这个帖子没有图片。"
}

### 获取所有帖子
GET {{baseUrl}}/api/infor-flow/view
Content-Type: application/json
Authorization: Bearer {{token}}

### 通过内容搜索帖子
POST {{baseUrl}}/api/infor-flow/view
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "test"
} 


### 通过内容搜索帖子
POST {{baseUrl}}/api/infor-flow/view
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "问答"
}

### 获取所有帖子
GET {{baseUrl}}/api/infor-flow/delete/9368f0e5-5378-48cf-9614-8e400d26984e
Content-Type: application/json
Authorization: Bearer {{token}}
